[package]
name = "epifanio"
version = "0.1.0"
authors = ["avdb13 <avdb@keemail.me>"]
readme = "README.md"
repository = "https://github.com/avdb13/epifanio"
license = "AGPL-3.0-or-later"
edition = "2021"

[dependencies]
rand = "0.8.5"
